name: Python

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Copy config
      run: cp config.example.py config.py
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox setuptools wheel
        pip install -r requirements.txt
    - name: Tox
      run: tox
    - name: Unit tests
      run: python tests.py
